sudo: false
language: c
dist: trusty
os: osx
before_install:
  - brew update
  - brew install valgrind
script:
  - unset TRAVIS_COMMIT_MESSAGE
  - git clone https://github.com/s-yakubovskiy/21_to_42sh.git
  - make re
  # - bash st/42ShellTester.sh --all --pending --reference bash $PWD/42sh
